### PR TITLE
Update body-parser to mitigate vulnerabilities

### PR DESCRIPTION
**Pull request by abstractj**
See: https://gist.github.com/abstractj/221f068e93d85c431d84#fh-cartridge-openshift

### CODE REVIEW

**Comment by abstractj** [comment]
@grdryn @wei-lee could you please take a look when possible?

**Comment by grdryn** [comment]
@jasonmadigan Looks like we missed one...this should have a shrinkwrap file, right? Also, should there be a job on jenkins to validate PRs?

**Comment by jasonmadigan** [comment]
@grdryn Yeah, this should be shrinkwrapped too. Unsure why we don't have a build job for this - any ideas @cianclarke?

**Comment by grdryn** [comment]
@jasonmadigan thanks for clarifying. @abstractj Can you add a shrinkwrap file along with this here then please? Running `npm shrinkwrap` will generate it.

**Comment by abstractj** [comment]
@grdryn @jasonmadigan morning my friends, done for this pull-request.

**Comment by cianclarke** [comment]
Looks good
No build job, as it needs to be a public repo - wasn't sure if this should be travis'd or some other means..

**Comment by abstractj** [comment]
@cianclarke do you think this PR is ready to merge? Or there's something that must be changed?

**Comment by cianclarke** [comment]
@abstractj Merged :-)

**Pull request merged**
